name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      imagetag:
        type: string
        description: Type imagetag to deploy
      azurelocation:
        type: string
        description: Type in the Azure Location for Deployment

jobs:
  Bicep-Deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      uses: azure/CLI@v1.0.9
      with:
        azcliversion: 2.49.0
        inlineScript: |
          az group create --resource-group ${{ secrets.AZURE_RG }} --location ${{ github.event.inputs.azurelocation }}

    - name: Azure Bicep Deploy
      uses: Azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy/main.bicep
        parameters: 'dockerImageNameTag=${{ github.event.inputs.imagetag }} appServiceName=loeme containerRegistryName=latzo acrResourceGroupName=Default'
        failOnStdErr: false
